#!/bin/bash
function Usage {
    echo "Usage:"
    echo "  diskof <filename>"
    exit
}

if [[ $# -eq 0 ]] || [[ $1 == "" ]]; then
    Usage
fi
ARGS=("$@")


DISKS=($(/bin/ls -d /mnt/*/))
for dir in "${DISKS[@]}"
do
    if [[ "$dir" == *"user"* ]]; then
        continue
    fi

    for INP in "${ARGS[@]}"; do
        if [[ "$INP" == "" ]]; then
            continue
        fi
        # prune and remove /mnt/user
        FULL=$(realpath "$INP")
        FULLPATH=$(echo "$FULL" | cut -d "/" -f4-100)

        CURRENT="$dir$FULLPATH"

        if [[ -f "$CURRENT" ]]; then
            echo "$CURRENT"
            ARGS=("${ARGS[@]/$INP}")
        fi
    done
done