#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

rm /usr/bin/cpref /usr/bin/cpref
rm /usr/bin/cpref /usr/bin/diskof

CPREF=$DIR"/cpref"
DISKOF=$DIR"/diskof"


chmod +x "$CPREF"
chmod +x "$DISKOF"

ln -s "$CPREF" /usr/bin/cpref
ln -s "$DISKOF" /usr/bin/diskof
